drop table if exists mailing cascade;
drop table if exists post_office cascade;
drop table if exists tracking cascade;

create table if not exists mailing (
    id bigint generated by default as identity not null,
    type varchar not null,
    index_recipient varchar(255) not null,
    address_recipient varchar(255) not null,
    name_recipient varchar(50) not null,
    constraint pk_mailing primary key (id)
);

create table if not exists post_office (
    id bigint generated by default as identity not null,
    index_office varchar(255) not null,
    name_office varchar(255) not null,
    address_office varchar(255) not null,
    constraint pk_office primary key (id)
);

create table if not exists tracking (
    id bigint generated by default as identity not null,
    mailing_id bigint not null references mailing(id),
    post_office_id bigint not null references post_office(id),
    created_date timestamp without time zone not null,
    status varchar not null
);